name: Combine Coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: bitcart/bitcart-actions/actions/setup-python@master

      - name: Install dependencies
        run: uv pip install coverage[toml]

      - name: Download all coverage data artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: coverage-data-*
          path: coverage-data/

      - name: Download all test results artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: test-results-*
          path: test-results-all/

      - name: Combine coverage
        run: |
          i=0
          for f in $(find coverage-data/ -name '.coverage'); do
            cp "$f" ".coverage.$i"
            i=$((i + 1))
          done
          coverage combine
          coverage html -d combined-coverage/
          coverage xml -o combined-coverage/coverage.xml
          coverage report --format=markdown > combined-coverage/summary.md
          echo "## Coverage Summary" | tee -a "$GITHUB_STEP_SUMMARY"
          cat combined-coverage/summary.md | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Upload combined results
        uses: actions/upload-artifact@v6
        with:
          name: combined-coverage
          path: combined-coverage/

      - name: Display test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Test Results
          path: test-results-all/**/junit.xml
          reporter: python-xunit

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: bitcart/bitcart-actions/actions/codecov@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          upload_test_results: "true"
          test_results_files: test-results-all/**/junit.xml

      - name: Delete intermediate artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            test-results-*
            coverage-*
            coverage-data-*
          failOnError: false
